@startuml slack_01

skinparam {
  ' カーディナリティ斜め対策
   linetype ortho
}

entity "ワークスペース" as ワークスペース {
  ワークスペースID
  --
  ワークスペース名
}

entity "チャネル" as チャネル {
  チャネルID
  --
  チャネル名
  ワークスペースID(FK)
}

entity "所属" as 所属 {
  チャネルID(FK)
  ユーザーID(FK)
  --
  脱退フラグ
}

note left of 所属
  実際のslackでは、
  1つのワークスペースに全員参加のチャネルが1つ必ず存在する。
  そのため、1つのワークスペースにある全チャネルから脱退した場合は
  ワークスペースから脱退したと考えられる。
end note

entity "ユーザー" as ユーザー {
  ユーザーID
  --
  ユーザー名
}

entity "メッセージ" as メッセージ {
  メッセージID
  --
  メッセージ
  投稿日
  ユーザーID(FK)
  チャネルID(FK)
}

entity "スレッド" as スレッド {
  メッセージID(FK)
  --
  トップメッセージID(FK)
}

note left of スレッド
  スレッド返信が発生した場合、作成される。
end note

ワークスペース ||..|{ チャネル
チャネル ||..o{ 所属
所属 }|..|| ユーザー
チャネル ||..o{ メッセージ
ユーザー ||..o{ メッセージ
メッセージ ||..|{ スレッド


@enduml