@startuml slack_01

skinparam {
  ' カーディナリティ斜め対策
   linetype ortho
}

entity "ワークスペース" as ワークスペース {
  ワークスペースID
  --
  ワークスペース名
}

entity "チャネル" as チャネル {
  チャネルID
  --
  チャネル名
  ワークスペースID(FK)
}

entity "所属" as 所属 {
  所属ID
  --
  チャネルID(FK)
  ユーザーID(FK)
}

note right of 所属
  実際のslackでは、
  1つのワークスペースに全員参加のチャネルが1つ必ず存在する。
end note

entity "ユーザー" as ユーザー {
  ユーザーID
  --
  ユーザー名
}

entity "メッセージ" as メッセージ {
  メッセージID
  --
  メッセージ
  投稿日
  ユーザーID(FK)
}

entity "スレッド" as スレッド {
  スレッドID
  --
  メッセージID(FK)
}

note right of スレッド
  メッセージがスレッドのトップだった場合、
  メッセージID = スレッドID
end note

ワークスペース ||..|{ チャネル
チャネル ||..o{ 所属
所属 }|..|| ユーザー
ユーザー ||..o{ メッセージ
メッセージ ||..|{ スレッド


@enduml