@startuml sushi_ordering_schema_01

skinparam {
  ' カーディナリティ斜め対策
   linetype ortho
}

' 顧客マスタ
entity "Customers" as Customers {
  * customer_id
  --
  * name
  * phone_number
  * created_at
    updated_at
    deleted_at
}

note top of Customers
  <b>補足</b>
  ・同姓同名の可能性があるためphone_numberも必須とする。
end note

' 商品マスタ
entity "Products" as Products {
  * product_id
  --
  * product_name
  * created_at
    updated_at
    deleted_at
}

' 商品金額テーブル
entity "Prices" as Prices {
  * price_id
  --
  * product_id<<FK>>
  * tax_id<<FK>>
  * price
  * started_at
    finished_at
    updated_at
    deleted_at
}

note left of Prices
  <b>補足</b>
  値上げや値下げなど、頻繁に変更がある可能性があるため
  商品マスタとは別で管理。（Sale時の一時的値下げなど）
  同じproductでも期間別に複数もてる想定。
end note

' 消費税マスタ
entity "Taxes" as Taxes {
  * tax_id
  --
  * tax_rate
  * started_at
    finished_at
}

' 注文テーブル
entity "Orders" as Orders {
  * order_id
  --
  * customer_id<<FK>>
    total_fee
    total_quantity
    paid_at
  * created_at
    updated_at
    deleted_at
}

note left of Orders
  <b>補足</b>
  total_fee（合計金額）を入れてみた。
  <b>理由</b>
  ・paid_at（支払い完了日）がnullではない場合、金額が変更することはほぼないと考える。
  ・合計額の参照は高頻度に起こると考える（売上管理やレシート発行など）。
  ・上記のため、毎回別テーブル参照して計算は処理が遅くなる要因と考えた。
end note

entity "OrderDetails" as OrderDetails {
  * order_detail_id
  --
  * order_id<<FK>>
  * product_id<<FK>>
  * price_id<<FK>>
    subtotal_fee
    quantity
  * without_wasabi
  * created_at
    updated_at
    deleted_at
}

note top of OrderDetails
  <b>補足</b>
  subtotal_fee（小計）をここで出しておくことにより
  Ordersではsubtotal_feeを合計するだけでtotal_fee（合計金額）が出せると考えた。
end note

Customers ||..o{ Orders
Orders ||..|{ OrderDetails
OrderDetails }o..|| Products
OrderDetails ||..|| Prices
Products ||..o{ Prices
Prices }o..|| Taxes

note as note1
  <b>補足</b>
  全テーブルにidを付与して主キーとした。
  <b>理由</b>
  ・id１つのみで外部参照できる利点があると考えた。
  ・他の値と違って変更される可能性がない。

  でも本当に必要か？が、よくわかっていない。
end note

@enduml