@startuml sushi_ordering_schema_01

skinparam {
  ' カーディナリティ斜め対策
   linetype ortho
}

' 顧客マスタ
entity "Customers" as Customers {
  * customer_id : uuid
  --
  * name : varchar
  * phone_number : varchar
  * created_at : timestamp
    updated_at : timestamp
    deleted_at : timestamp
}

note top of Customers
  <b>補足</b>
  ・同姓同名の可能性があるためphone_numberも必須とする。
end note

' 商品マスタ
entity "Products" as Products {
  * product_id : uuid
  --
  * product_name : varchar
  * created_at : timestamp
    updated_at : timestamp
    deleted_at : timestamp
}

' 商品金額テーブル
entity "Prices" as Prices {
  * price_id : uuid
  --
  * product_id : uuid <<FK>>
  * tax_id : uuid <<FK>>
  * price : integer
  * started_at : timestamp
    finished_at : timestamp
    updated_at : timestamp
    deleted_at : timestamp
}

note left of Prices
  <b>補足</b>
  値上げや値下げなど、頻繁に変更がある可能性があるため
  商品マスタとは別で管理。（Sale時の一時的値下げなど）
  同じproductでも期間別に複数もてる想定。
end note

' 消費税マスタ
entity "Taxes" as Taxes {
  * tax_id : uuid
  --
  * tax_rate : real
  * started_at : timestamp
    finished_at : timestamp
}

' 注文テーブル
entity "Orders" as Orders {
  * order_id : uuid
  --
  * customer_id : uuid <<FK>>
    total_fee : integer
    paid_at : timestamp
  * created_at : timestamp
    updated_at : timestamp
    deleted_at : timestamp
}

note left of Orders
  <b>補足</b>
  total_fee（合計金額）を入れてみた。
  <b>理由</b>
  ・paid（支払済み）がtrueの場合、金額が変更することはほぼないと考える。
  ・合計額の参照は高頻度に起こると考える（売上管理やレシート発行など）。
  ・上記のため、毎回別テーブル参照して計算は処理が遅くなる要因と考えた。
end note

entity "OrderDetails" as OrderDetails {
  * order_detail_id : uuid
  --
  * order_id : uuid <<FK>>
  * product_id : uuid <<FK>>
  * price_id : uuid <<FK>>
    subtotal_fee : integer
    quantity : smallint
  * without_wasabi : boolean
  * created_at : timestamp
    updated_at : timestamp
    deleted_at : timestamp
}

note top of OrderDetails
  <b>補足</b>
  subtotal_fee（小計）をここで出しておくことにより
  Ordersではsubtotal_feeを合計するだけでtotal_fee（合計金額）が出せると考えた。
end note

Customers ||..o{ Orders
Orders ||..|{ OrderDetails
OrderDetails }o..|| Products
OrderDetails ||..|| Prices
Products ||..o{ Prices
Prices }o..|| Taxes

note as note1
  <b>補足</b>
  全テーブルにidを付与して主キーとした。
  <b>理由</b>
  ・id１つのみで外部参照できる利点があると考えた。
  ・他の値と違って変更される可能性がない。

  でも本当に必要か？が、よくわかっていない。
end note

@enduml